console.log("==============================================");
console.log('process.env ', process.env);
console.log("==============================================");
console.log('process.argv ', process.argb);
console.log("==============================================");
console.log('Directorio actual de trabajo: ', process.cwd());
console.log("==============================================");
console.log('Id del proceso: ', process.pid);
console.log("==============================================");
console.log('Version de node: ', process.version);
console.log("==============================================");
console.log('Título de proceso: ', process.title);
console.log("==============================================");
console.log('Sistema operativo: ', process.platform);
console.log("==============================================");
console.log('Uso de la memoria: ', process.memoryUsage());
console.log("==============================================");